name: "DEV PROD"

on:
  push:
    branches:
       - master # trocar isso depois para main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "{{recurso-criado-manualmente-na-aws}}"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "{{recurso-criado-manualmente-na-aws}}"
      aws-lock-dynamodb-table: "{{recurso-criado-manualmente-na-aws}}"
